@startuml "ADS fault"
<style>
note {
  .red {
        BackgroundColor red
   }
}
</style>

skinparam ConditionEndStyle hline
title Critical event on ADS trip

start
note left: Driving

:ADS detects fault or event;
:Notify users;

if (Is critical?) equals(yes) then
    :ADS performs MRM;
    note left: MRS

    if(Is active supervision possible?) equals (yes) then

        group Technical Supervisor
            :Identify and analyze fault;
            if(Is DDT possible?) equals (yes) then

                repeat :Analyze scenario;
                :Suggests/approves maneuver to achieve\n DDT (DDTM) or perform commands/fixes;
                repeat while (ADS self-checks) is (red) not (green)

                if (Can ADS continue \n DDT normally?) equals (no) then
                    label aux_label
                    :ADS continue DDT;
                    note left: DegradedDriving
                    -> After trip ends;
                    stop
                    note left: InReparation
                else (yes)
                endif
                
            else (no)
                :Analyze MRS state;
                if (Is MRS optimal?) equals (yes) then
                    :Mark ADS to be repaired;
                    end
                    note right: InReparation
                else (no)
                    while (MRS can be better)
                        :Analyze scenario;
                        :Suggest and perform MRM 
                        or commands/fixes;
                    endwhile
                    :Mark ADS to be repaired;
                    note left: MRS'
                    end
                    note left: InReparation
                endif
            endif

            
        end group                
        
        :ADS continue DDT;
        note right: Driving
        -> After trip ends;
        stop
        note left: StandBy
    else (no)
        label space_label
        end
        note left: MRS
    endif
else (no)
    label degraded_ddt
    :ADS continue DDT;
    note left: DegradedDriving
    -> After trip ends;
    stop
    note left: InReparation
endif
@enduml
