@startuml "ADS fault"

skinparam ConditionEndStyle hline
title Elevated risk situations: TS-ADS workflow

:Vehicle with a fault;

floating note right
    Users: Technical supervisors
    MRM: Minimum risk maneuver
    MRC: Minimum risk condition
    MRDS: ?
end note

switch (User intervention required)

case (no)
    label space_label_1
    label space_label_2
    label space_label_3
    label space_label_5
    label space_label_5
    label autonomous_mrm
    :Vehicle performs MRM autonomously;

    if(MRM successful) equals (yes) then
        :Vehicle in MRC;
        :Notify users;
    else (no)
        end
    endif
    stop

case (yes)
    :Notify users;

    if (Request active supervision from TS) equals (not approved) then
        label not_approved
        goto autonomous_mrm

    else (not approved)

        :Initial diagnose based on extensive
        real-time vehicle data;
        
        note left
            Car state
            Sensor stream
            Context data
            Historic data
        end note

        while(Continuous data analysis.\n Vehicle suitable for MRC?) is (no)
            if (MRM required) equals (yes) then
                :Choose MRM from
                suggestions or propose one;
                :Approve and perform MRM;

                if(MRM successful) equals (yes) then
                else (no)
                endif

            else (no)
                :Issue commands and
                perform changes;
            endif

        endwhile (yes)

        :Confirm vehicle MRC;
        :End supervision;

        stop
    endif


@enduml
