@startuml "ADS fault"
start
skinparam ConditionEndStyle hline
title Critical event in active ADS

:ADS detects fault or event;
:Notify users;

    if (Is critical?) equals(yes) then
        :MRM performed by vehicle;
        :Vehicle in MRC;

        if(Is active supervision possible?) equals (yes) then
            
            group Active Technical Supervisor
                while(Is valid MRC?) is (no)
                    :- Send commands
                    - Suggest MRM;
                endwhile (yes)

                :Confirm MRC;
                :Vehicle suggests valid 
                maneuvers to go back to DDT (DDTM);
                :Confirm DDTM;
            end group
            : Vehicle in NominalDriving;
            stop
        else (no)
            label space_label
            :Notify users;
            end
        endif

    ' Could it be that a vehicle detects a critical flaw, knows what MRMs to perform and he will tell the user???

    else (no)
        :Vehicle in DegradedDriving;
        stop
    endif
@enduml
