@startuml ts_use_cases
title Technical supervisor use cases

left to right direction

actor :Technical\nSupervisor: as TS1

package "Technical Supervisor App" {
    usecase UC4 as (Login) <<  UC1  >>
    usecase UC5 as (Log out) <<  UC11  >>
    usecase UC3 as (Change geozone) <<  UC10  >>

    ' Supervise system
    rectangle Monitor {
        usecase UC100 as (Approve trip start) <<  UC2  >>
        usecase UC101 as (Analyze system summary) <<  UC3  >>
        usecase UC102 as (List ADS) <<  UC4  >>
        usecase UC104 as (Perform ADS routine tests) <<  UC5  >>
        usecase UC105 as (Monitor ODD) <<  UC6  >>
        usecase UC106 as (Suggest trip route) << UC1.1 >>

    }

    rectangle Act {
        ' Supervise ADS
        usecase UC202 as (Approve DDTM to go out of MRC) <<  UC7  >>
        ' ADS actions
        usecase UC303 as (Suggest DDTM) <<  UC7.1  >>
        usecase UC304 as (Send ADV commands) <<  UC8  >>
        usecase UC305 as (Deactivate ADS) <<  UC9  >>
    }
}

' User connections
TS1 -up-> UC4
UC3 --> UC4 : <<extends>>
UC5 --> UC4 : <<includes>>

' Supervise system
UC100 -> UC4 : <<extends>>
UC101 -> UC4 : <<extends>>
UC102 -> UC4 : <<extends>>
UC104 -> UC4 : <<extends>>
UC105 -> UC4 : <<extends>>
UC106 --> UC100 : <<extends>>

' Supervise ADS
UC202 -> UC4 : <<extends>>
UC303 --> UC202 : <<extends>>
UC304 -> UC4 : <<extends>>
UC305 -> UC4 : <<extends>>

@enduml
