@startuml
skinparam nodesep 10
skinparam ranksep 5

scale 1.0

node "Technical supervisor system" as ts {
    rectangle "Backend services" as backend {
        component "MQTT client" as ads_client
    }
}

component "MQTT Broker" as mqtt_broker

node "ADS1" as ads { 
    node "ROS" as ads1 {
        component "Orchestrator" as ads_orchestrator
        component "MQTT Bridge node" as ads_mqtt_node
    }
}

ads_client <-> mqtt_broker
ads_mqtt_node <-> mqtt_broker

@enduml
