@startuml
skinparam nodesep 10
skinparam ranksep 5

scale 1.0

node "Technical supervisor system" as ts {
    rectangle "Backend services" as backend {
        component "GRPC client" as ads_client
    }
}

node "ADS1" as ads { 
    node "ROS" as ads1 {
        component "Orchestrator" as ads_orchestrator
    }
    component "GRPC Server" as grpc_server
}

ads_client <-> grpc_server

@enduml
