@startuml ts_use_cases
title Technical supervisor use cases

left to right direction

actor :Technical\nSupervisor: as USER

package "Technical Supervisor App" {
    usecase TS1 as (MONITOR)<<  TS1  >>
    usecase TS2 as (ACT) <<  TS2  >>
    usecase TS3 as (Receive notifications) <<  TS3  >>
    usecase TS4 as (Login) <<  TS4  >>
    usecase TS5 as (Log out) <<  TS5  >>

    usecase TS301 as (Mark notifications as read) <<  TS3.1  >>

    ' Monitor
    usecase TS102 as (Monitor ADS) <<  TS1.1  >>
    usecase TS100 as (Approve trip start) <<  TS1.2  >>
    usecase TS107 as (List ADS) <<  TS1.1.1  >>
    usecase TS101 as (Supervise ADS) <<  TS1.1.2  >>
    usecase TS104 as (Perform ADS routine tests) <<  TS1.3  >>
    usecase TS105 as (Monitor ODD) <<  TS1.4  >>
    usecase TS106 as (Suggest trip route) << TS1.2.1 >>
    usecase TS108 as (Change geozone) <<  TS1.6  >>
    usecase TS109 as (Request leave) <<  TS1.7  >>

    ' Act
    usecase TS201 as (Approve DDTM to go out of MRS) <<  TS2.1  >>
    usecase TS202 as (Suggest DDTM) <<  TS2.1.1  >>
    usecase TS203 as (Mark ADS for workshop) <<  TS2.2  >>
    usecase TS204 as (Communicate with ADS passengers) <<  TS2.3  >>
    usecase TS205 as (Monitor ADS passengers) <<  TS2.4  >>
    usecase TS206 as (Send ADV commands) <<  TS2.5  >>
    usecase TS207 as (Deactivate ADS) <<  TS2.6  >>
    usecase TS208 as (Submit ADS feedback) <<  TS2.7  >>  
}

' General use cases
USER -up-> TS4
TS2 -> TS4 #line.dashed : <<extends>> 
TS1 ---> TS4 : <<includes>> 
TS5 --> TS4 : <<includes>>
TS3 -> TS4 #line.dashed : <<extends>>
TS301 -> TS3 #line.dashed : <<extends>>

' Monitor
TS100 --> TS1 #line.dashed : <<extends>>
TS106 --> TS100 #line.dashed : <<extends>>
TS101 --> TS102 #line.dashed : <<extends>>
TS102 --> TS1 : <<includes>>
TS104 --> TS1 #line.dashed : <<extends>>
TS105 --> TS1 #line.dashed : <<extends>>
TS107 --> TS102 #line.dashed : <<extends>>
TS108 -d-> TS1 #line.dashed : <<extends>>
TS109 --> TS1 #line.dashed : <<extends>>

' Act
TS201 --> TS2 #line.dashed : <<extends>>
TS202 --> TS201 #line.dashed : <<extends>>
TS203 --> TS2 #line.dashed : <<extends>>
TS204 --> TS2 #line.dashed : <<extends>>
TS205 --> TS2 #line.dashed : <<extends>>
TS206 --> TS2 #line.dashed : <<extends>>
TS207 --> TS2 #line.dashed : <<extends>>
TS208 --> TS2 #line.dashed : <<extends>>

@enduml
