@startuml ts_use_cases
title Admin supervisor use cases

left to right direction

actor :Admin\nSupervisor: as ADM1

package "Technical Supervisor App" {
    usecase AS1 as (Login) <<  AS1  >>
    usecase AS2 as (Log out) <<  AS2  >>
    usecase AS3 as (Manage ADS) <<  AS3  >>
    usecase AS4 as (Manage ODD) <<  AS4  >>
    usecase AS5 as (Manage geozones) <<  AS5  >>
    usecase AS6 as (Manage users) <<  AS6  >>
    usecase AS7 as (Manage user roles) <<  AS7  >>
    usecase AS8 as (Manage user permissions) <<  AS8  >>

    usecase AS501 as (Manage landmarks) <<  AS5.1  >>
    usecase AS9 as (Resolve absence requests) <<  AS9  >>
}

ADM1 -up-> AS1

AS2 -> AS1 : <<includes>> 
AS3 --> AS1 #line.dashed : <<extends>>
AS4 --> AS1 #line.dashed : <<extends>>
AS5 --> AS1 #line.dashed : <<extends>>
AS6 --> AS1 #line.dashed : <<extends>>
AS7 --> AS1 #line.dashed : <<extends>>
AS8 --> AS1 #line.dashed : <<extends>>
AS501 -d-> AS5 #line.dashed : <<extends>>
AS9 --> AS1 #line.dashed : <<extends>>

@enduml
