@startuml ts_use_cases
title Technical supervisor use cases

left to right direction

actor :Technical\nSupervisor: as TS1

package "Technical Supervisor App" {
    usecase UC4 as (Login) <<  UC4  >>
    usecase UC5 as (Log out) <<  UC5  >>
    usecase UC1 as (MONITOR)<<  UC1  >>
    usecase UC2 as (ACT) <<  UC2  >>

    ' Supervise system
    usecase UC102 as (Monitor ADS on map) <<  UC1.1  >>
    usecase UC100 as (Approve trip start) <<  UC1.2  >> #DarkSalmon
    usecase UC101 as (Analyze system summary) <<  UC1.3  >>
    usecase UC104 as (Perform ADS routine tests) <<  UC1.4  >>
    usecase UC105 as (Monitor ODD) <<  UC1.5  >>
    usecase UC106 as (Suggest trip route) << UC1.2.1 >> #DarkSalmon
    usecase UC107 as (List ADS) <<  UC1.6  >>
    usecase UC108 as (Change geozone) <<  UC1.7  >>
    usecase UC109 as (Pause availability) <<  UC1.8  >>

    ' Supervise ADS
    usecase UC201 as (Approve DDTM to go out of MRS) <<  UC2.1  >>
    usecase UC202 as (Suggest DDTM) <<  UC2.1.1  >>
    usecase UC203 as (Mark ADS for workshop) <<  UC2.2  >>
    usecase UC204 as (Communicate with ADS passengers) <<  UC2.3  >>
    usecase UC205 as (Monitor ADS passengers) <<  UC2.4  >>
    usecase UC206 as (Send ADV commands) <<  UC2.5  >>
    usecase UC207 as (Deactivate ADS) <<  UC2.6  >>
    usecase UC208 as (Submit ADS feedback) <<  UC2.7  >>  
}

' User connections
TS1 -up-> UC4
UC2 -> UC4 #line.dashed : <<extends>> 
UC1 ---> UC4 : <<includes>> 
UC5 --> UC4 : <<includes>>

' Supervise system
UC100 --> UC1 #line.dashed : <<extends>>
UC106 --> UC100 #line.dashed : <<extends>>
UC101 --> UC1 #line.dashed : <<extends>>
UC102 --> UC1 : <<includes>>
UC104 --> UC1 #line.dashed : <<extends>>
UC105 --> UC1 #line.dashed : <<extends>>
UC107 --> UC1 #line.dashed : <<extends>>
UC108 -d-> UC1 #line.dashed : <<extends>>
UC109 --> UC1 #line.dashed : <<extends>>

' Supervise ADS
UC201 --> UC2 #line.dashed : <<extends>>
UC202 --> UC201 #line.dashed : <<extends>>
UC203 --> UC2 #line.dashed : <<extends>>
UC204 --> UC2 #line.dashed : <<extends>>
UC205 --> UC2 #line.dashed : <<extends>>
UC206 --> UC2 #line.dashed : <<extends>>
UC207 --> UC2 #line.dashed : <<extends>>
UC208 --> UC2 #line.dashed : <<extends>>

@enduml
