@startuml ts_use_cases
title Admin supervisor use cases

left to right direction

actor :Admin\nSupervisor: as ADM1

package "Technical Supervisor App" {
    usecase UC1 as (Login) <<  UC1  >>
    usecase UC2 as (Log out) <<  UC2  >>
    usecase UC3 as (Manage ADS) <<  UC3  >>
    usecase UC4 as (Manage ODD) <<  UC4  >>
    usecase UC5 as (Manage geozones) <<  UC5  >>
    usecase UC6 as (Manage users) <<  UC6  >>
    usecase UC7 as (Manage user roles) <<  UC7  >>
    usecase UC8 as (Manage user permissions) <<  UC8  >>

    usecase UC61 as (Assign geozones) <<  UC6.1  >>
    usecase UC62 as (Read user logs) <<  UC6.2  >>
}

ADM1 -up-> UC1

UC2 -> UC1 : <<includes>> 
UC3 --> UC1 #line.dashed : <<extends>>
UC4 --> UC1 #line.dashed : <<extends>>
UC5 --> UC1 #line.dashed : <<extends>>
UC6 --> UC1 #line.dashed : <<extends>>
UC61 --> UC6 #line.dashed : <<extends>>
UC62 --> UC6 #line.dashed : <<extends>>
UC7 --> UC1 #line.dashed : <<extends>>
UC8 --> UC1 #line.dashed : <<extends>>

@enduml
